"""
Event type mappings for Aritech ATS alarm panel.

Extracted from decompiled Android app sources.
357 event types total.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class EventCategory(StrEnum):
    """Event categories."""

    IGNORED = "Ignored"
    RESTORE = "Restore"
    TROUBLE = "Trouble"
    ALARM = "Alarm"
    INFO = "Info"
    ACCESS = "Access"
    SET_PARTSET = "Set_Partset"
    UNSET = "Unset"
    PICTURE = "Picture"
    UNKNOWN = "Unknown"


@dataclass(frozen=True, slots=True)
class EventType:
    """Event type definition."""

    code: str
    name: str
    category: EventCategory


# Event type enum with descriptions (357 types)
EVENT_TYPES: dict[int, EventType] = {
    0: EventType("ev_NULL", "NULL", EventCategory.IGNORED),
    1: EventType("ev_AN", "Detector dirty restore", EventCategory.RESTORE),
    2: EventType("ev_ARZN", "AC restore (Technical Zone)", EventCategory.RESTORE),
    3: EventType("ev_ARDGP", "AC Restore", EventCategory.RESTORE),
    4: EventType("ev_AS", "Detector dirty", EventCategory.TROUBLE),
    5: EventType("ev_ATZN", "AC trouble (Technical Zone)", EventCategory.TROUBLE),
    6: EventType("ev_ATDGP", "AC Fault", EventCategory.TROUBLE),
    7: EventType("ev_BA", "Alarm", EventCategory.ALARM),
    8: EventType("ev_BB", "Alarm inhibit", EventCategory.INFO),
    9: EventType("ev_BCUSER", "Cancel by user", EventCategory.ACCESS),
    10: EventType("ev_BCKEY", "Cancel by key", EventCategory.ACCESS),
    11: EventType("ev_BCPC", "Cancel by PC", EventCategory.ACCESS),
    12: EventType("ev_BJ", "Detector supervision restore", EventCategory.RESTORE),
    13: EventType("ev_BR", "Burglar restore", EventCategory.RESTORE),
    14: EventType("ev_BT", "Input in mask/trouble when disarmed", EventCategory.TROUBLE),
    15: EventType("ev_BU", "Alarm uninhibit", EventCategory.INFO),
    16: EventType("ev_BV", "Alarm confirm", EventCategory.ALARM),
    17: EventType("ev_BW", "Restore confirmed alarm", EventCategory.RESTORE),
    18: EventType("ev_BZ", "Detector supervision", EventCategory.TROUBLE),
    19: EventType("ev_CFUSER", "Forced set by user", EventCategory.SET_PARTSET),
    20: EventType("ev_CFKEY", "Forced set by key", EventCategory.SET_PARTSET),
    21: EventType("ev_CFPC", "Forced set by PC", EventCategory.SET_PARTSET),
    22: EventType("ev_CGUSER", "Part set by user", EventCategory.SET_PARTSET),
    23: EventType("ev_CGKEY", "Part set by key", EventCategory.SET_PARTSET),
    24: EventType("ev_CGPC", "Part set by PC", EventCategory.SET_PARTSET),
    25: EventType("ev_CLUSER", "Set by user", EventCategory.SET_PARTSET),
    26: EventType("ev_CLKEY", "Set by key", EventCategory.SET_PARTSET),
    27: EventType("ev_CLPC", "Set by PC", EventCategory.SET_PARTSET),
    28: EventType("ev_EEUSER", "Exit fault by user", EventCategory.ALARM),
    29: EventType("ev_EESYST", "Exit fault by system", EventCategory.INFO),
    30: EventType("ev_ERDGP", "Expander trouble restore", EventCategory.INFO),
    31: EventType("ev_ERDGPC", "Expander communication restore", EventCategory.RESTORE),
    32: EventType("ev_ERDGPF", "Expander fuse restore", EventCategory.RESTORE),
    33: EventType("ev_ERRAS", "Keypad trouble restore", EventCategory.RESTORE),
    34: EventType("ev_ERRASC", "Keypad communication restore", EventCategory.RESTORE),
    35: EventType("ev_ETDGP", "Expander trouble", EventCategory.TROUBLE),
    36: EventType("ev_ETDGPC", "Expander communication fail", EventCategory.INFO),
    37: EventType("ev_ETDGPF", "Expander fuse fault", EventCategory.TROUBLE),
    38: EventType("ev_ETRAS", "Keypad trouble", EventCategory.TROUBLE),
    39: EventType("ev_ETRASC", "Keypad communication fail", EventCategory.INFO),
    40: EventType("ev_FA", "Fire", EventCategory.ALARM),
    41: EventType("ev_FB", "Fire inhibit", EventCategory.INFO),
    42: EventType("ev_FJ", "Fire trouble restore", EventCategory.RESTORE),
    43: EventType("ev_FR", "Fire restore", EventCategory.RESTORE),
    44: EventType("ev_FT", "Fire trouble", EventCategory.TROUBLE),
    45: EventType("ev_FU", "Fire uninhibit", EventCategory.INFO),
    46: EventType("ev_FW", "Fire supervision long", EventCategory.TROUBLE),
    47: EventType("ev_HA", "Duress", EventCategory.ALARM),
    48: EventType("ev_HR", "Duress restore", EventCategory.RESTORE),
    49: EventType("ev_JP", "Service in", EventCategory.INFO),
    50: EventType("ev_JR", "Service out", EventCategory.INFO),
    51: EventType("ev_JT", "Time changed", EventCategory.INFO),
    52: EventType("ev_LB", "Local programming start", EventCategory.INFO),
    53: EventType("ev_LS", "Local programming stop", EventCategory.INFO),
    54: EventType("ev_LR", "Line restore", EventCategory.RESTORE),
    55: EventType("ev_LT", "Line fault", EventCategory.TROUBLE),
    56: EventType("ev_MA", "Medical alarm", EventCategory.ALARM),
    57: EventType("ev_MB", "Medical bypass", EventCategory.INFO),
    58: EventType("ev_MJ", "Medical supervision restore", EventCategory.RESTORE),
    59: EventType("ev_MR", "Medical restore", EventCategory.RESTORE),
    60: EventType("ev_MU", "Medical unbypass", EventCategory.INFO),
    61: EventType("ev_MS", "Medical supervision long", EventCategory.TROUBLE),
    62: EventType("ev_OPUSER", "Unset by user", EventCategory.UNSET),
    63: EventType("ev_OPKEY", "Unset by key", EventCategory.UNSET),
    64: EventType("ev_OPPC", "Unset by PC", EventCategory.UNSET),
    65: EventType("ev_ORUSER", "Unset from alarm by user", EventCategory.UNSET),
    66: EventType("ev_ORKEY", "Unset from alarm by key", EventCategory.UNSET),
    67: EventType("ev_ORPC", "Unset from alarm by PC", EventCategory.UNSET),
    68: EventType("ev_PA", "Panic", EventCategory.ALARM),
    69: EventType("ev_PB", "Panic bypass", EventCategory.INFO),
    70: EventType("ev_PJ", "Panic trouble restore", EventCategory.RESTORE),
    71: EventType("ev_PR", "Panic restore", EventCategory.RESTORE),
    72: EventType("ev_PT", "Panic trouble", EventCategory.TROUBLE),
    73: EventType("ev_PU", "Panic unbypass", EventCategory.INFO),
    74: EventType("ev_RB", "Remote programming start", EventCategory.INFO),
    75: EventType("ev_RR", "Power up system", EventCategory.INFO),
    76: EventType("ev_RRDGP", "Power up Expander", EventCategory.INFO),
    77: EventType("ev_RRRAS", "Power up Keypad", EventCategory.INFO),
    78: EventType("ev_RS", "Remote programming success", EventCategory.INFO),
    79: EventType("ev_RU", "Remote programming fail", EventCategory.INFO),
    80: EventType("ev_RX", "Manual CS test", EventCategory.INFO),
    81: EventType("ev_TA", "Tamper zone", EventCategory.ALARM),
    82: EventType("ev_TADGP", "Tamper Expander", EventCategory.ALARM),
    83: EventType("ev_TADGPS", "Tamper Expander siren", EventCategory.TROUBLE),
    84: EventType("ev_TARAS", "Tamper Keypad", EventCategory.ALARM),
    85: EventType("ev_TB", "Tamper bypass", EventCategory.INFO),
    86: EventType("ev_TR", "Tamper zone restore", EventCategory.RESTORE),
    87: EventType("ev_TRDGP", "Tamper Expander restore", EventCategory.RESTORE),
    88: EventType("ev_TRDGPS", "Tamper Expander siren restore", EventCategory.RESTORE),
    89: EventType("ev_TRRAS", "Tamper Keypad restore", EventCategory.RESTORE),
    90: EventType("ev_TU", "Tamper unbypass", EventCategory.INFO),
    91: EventType("ev_UBDGP", "Expander bypass", EventCategory.INFO),
    92: EventType("ev_UBRAS", "Keypad bypass", EventCategory.INFO),
    93: EventType("ev_UBZN", "Zone bypass", EventCategory.INFO),
    94: EventType("ev_UUDGP", "Expander unbypass", EventCategory.INFO),
    95: EventType("ev_UURAS", "Keypad unbypass", EventCategory.INFO),
    96: EventType("ev_UUZN", "Zone unbypass", EventCategory.INFO),
    97: EventType("ev_WP", "Walk test passed", EventCategory.INFO),
    98: EventType("ev_WF", "Walk test fault", EventCategory.INFO),
    99: EventType("ev_XH", "RF jamming restore", EventCategory.RESTORE),
    100: EventType("ev_XQ", "RF jamming", EventCategory.TROUBLE),
    101: EventType("ev_XR", "Detector low battery restore", EventCategory.RESTORE),
    102: EventType("ev_XT", "Detector low battery", EventCategory.TROUBLE),
    103: EventType("ev_YC", "Communications device fault", EventCategory.TROUBLE),
    104: EventType("ev_YK", "FTC restore", EventCategory.RESTORE),
    105: EventType("ev_YR", "Battery restore", EventCategory.RESTORE),
    106: EventType("ev_YS", "FTC", EventCategory.TROUBLE),
    107: EventType("ev_YT", "Battery fault", EventCategory.TROUBLE),
    108: EventType("ev_ZA", "Technical", EventCategory.ALARM),
    109: EventType("ev_ZB", "Technical bypass", EventCategory.INFO),
    110: EventType("ev_ZJ", "Technical supervision restore", EventCategory.RESTORE),
    111: EventType("ev_ZR", "Technical restore", EventCategory.RESTORE),
    112: EventType("ev_ZS", "Technical supervision long", EventCategory.TROUBLE),
    113: EventType("ev_ZU", "Technical unbypass", EventCategory.INFO),
    114: EventType("ev_OUTA", "Output activated", EventCategory.INFO),
    115: EventType("ev_OUTR", "Output restored", EventCategory.RESTORE),
    116: EventType("ev_USRG", "User access granted", EventCategory.ACCESS),
    117: EventType("ev_USRD", "User access denied", EventCategory.ACCESS),
    118: EventType("ev_EROK", "Engineer reset", EventCategory.RESTORE),
    119: EventType("ev_INTEG", "Stack integrity error", EventCategory.TROUBLE),
    120: EventType("ev_WDG", "Watchdog error", EventCategory.TROUBLE),
    121: EventType("ev_CHKSUM", "Flash memory checksum error", EventCategory.TROUBLE),
    122: EventType("ev_USRADD", "User added", EventCategory.INFO),
    123: EventType("ev_USRDEL", "User deleted", EventCategory.INFO),
    124: EventType("ev_USRPIN", "PIN changed", EventCategory.INFO),
    125: EventType("ev_USRTAMP", "PIN tamper", EventCategory.ALARM),
    126: EventType("ev_ZNNTST", "Zone not tested", EventCategory.INFO),
    127: EventType("ev_BJS", "Detector supervision restore", EventCategory.RESTORE),
    128: EventType("ev_BZS", "Detector supervision", EventCategory.TROUBLE),
    129: EventType("ev_INSTRST", "Recovery proc", EventCategory.INFO),
    130: EventType("ev_TT", "Key box open", EventCategory.ALARM),
    131: EventType("ev_KBTR", "Key box restore", EventCategory.RESTORE),
    132: EventType("ev_YTL", "Battery low", EventCategory.TROUBLE),
    133: EventType("ev_OVRD", "Fault/Alarm overrided", EventCategory.INFO),
    134: EventType("ev_YA", "Tamper Expander siren", EventCategory.TROUBLE),
    135: EventType("ev_YH", "Tamper Expander siren restore", EventCategory.RESTORE),
    136: EventType("ev_NC", "CS poll fault", EventCategory.TROUBLE),
    137: EventType("ev_NR", "CS poll restored", EventCategory.RESTORE),
    138: EventType("ev_LTETH", "ETH link fault", EventCategory.TROUBLE),
    139: EventType("ev_LTIP", "IP config fault", EventCategory.TROUBLE),
    140: EventType("ev_LRIP", "IP configured", EventCategory.RESTORE),
    141: EventType("ev_JTSYS", "Time changed", EventCategory.INFO),
    142: EventType("ev_YSSYS", "Global FTC", EventCategory.TROUBLE),
    143: EventType("ev_YKSYS", "Global FTC restore", EventCategory.RESTORE),
    144: EventType("ev_RP", "Automatic CS test", EventCategory.INFO),
    145: EventType("ev_SMSUN", "Unknown SMS", EventCategory.INFO),
    146: EventType("ev_SMSLIM", "SMS sending limit reached", EventCategory.TROUBLE),
    147: EventType("ev_YKMI", "Communications device restore", EventCategory.RESTORE),
    148: EventType("ev_LTGPRS", "GPRS link fault", EventCategory.TROUBLE),
    149: EventType("ev_LTIPGPRS", "GPRS IP config fault", EventCategory.TROUBLE),
    150: EventType("ev_LRIPGPRS", "GPRS IP configured", EventCategory.RESTORE),
    151: EventType("ev_CFRAS", "Quick set", EventCategory.SET_PARTSET),
    152: EventType("ev_CGRAS", "Quick part set", EventCategory.SET_PARTSET),
    153: EventType("ev_CP", "Auto set", EventCategory.SET_PARTSET),
    154: EventType("ev_OA", "Auto unset", EventCategory.UNSET),
    155: EventType("ev_OT", "Late close", EventCategory.ALARM),
    156: EventType("ev_OK", "Early open", EventCategory.ALARM),
    157: EventType("ev_AASTOPU", "Autoset stopped by user", EventCategory.UNSET),
    158: EventType("ev_AASTOPS", "Autoset stopped by system", EventCategory.UNSET),
    159: EventType("ev_PARAS", "Panic", EventCategory.ALARM),
    160: EventType("ev_PAUSR", "Panic", EventCategory.ALARM),
    161: EventType("ev_IA", "Engineer reset required", EventCategory.TROUBLE),
    162: EventType("ev_CA", "Card assigned", EventCategory.INFO),
    163: EventType("ev_CR", "Card removed", EventCategory.INFO),
    164: EventType("ev_GA", "Gas alarm", EventCategory.ALARM),
    165: EventType("ev_GR", "Gas alarm restore", EventCategory.RESTORE),
    166: EventType("ev_GB", "Gas alarm inhibit", EventCategory.INFO),
    167: EventType("ev_GU", "Gas alarm uninhibit", EventCategory.INFO),
    168: EventType("ev_GS", "Gas zone supervision", EventCategory.ALARM),
    169: EventType("ev_GJ", "Gas supervision restore", EventCategory.RESTORE),
    170: EventType("ev_KA", "Heat alarm", EventCategory.ALARM),
    171: EventType("ev_KR", "Heat alarm restore", EventCategory.RESTORE),
    172: EventType("ev_KB", "Heat alarm inhibit", EventCategory.INFO),
    173: EventType("ev_KU", "Heat alarm uninhibit", EventCategory.INFO),
    174: EventType("ev_KS", "Heat zone supervision", EventCategory.ALARM),
    175: EventType("ev_KJ", "Heat supervision restore", EventCategory.RESTORE),
    176: EventType("ev_WA", "Water alarm", EventCategory.ALARM),
    177: EventType("ev_WR", "Water alarm restore", EventCategory.RESTORE),
    178: EventType("ev_WB", "Water alarm inhibit", EventCategory.INFO),
    179: EventType("ev_WU", "Water alarm uninhibit", EventCategory.INFO),
    180: EventType("ev_WS", "Water zone supervision", EventCategory.ALARM),
    181: EventType("ev_WJ", "Water supervision restore", EventCategory.RESTORE),
    182: EventType("ev_CLRAS", "Set by user", EventCategory.INFO),
    183: EventType("ev_HV", "Confirmed panic alarm", EventCategory.ALARM),
    184: EventType("ev_HW", "Restore confirmed panic alarm", EventCategory.RESTORE),
    185: EventType("ev_EEZONE", "Exit fault by zone", EventCategory.ALARM),
    186: EventType("ev_UA", "Generic technical alarm", EventCategory.ALARM),
    187: EventType("ev_UR", "Generic technical alarm restore", EventCategory.RESTORE),
    188: EventType("ev_FARAS", "Fire", EventCategory.ALARM),
    189: EventType("ev_MARAS", "Medical alarm", EventCategory.ALARM),
    190: EventType("ev_FRRAS", "Fire restore", EventCategory.RESTORE),
    191: EventType("ev_MRRAS", "Medical restore", EventCategory.RESTORE),
    192: EventType("ev_PRRAS", "Panic restore", EventCategory.RESTORE),
    193: EventType("ev_PRUSR", "Panic restore", EventCategory.RESTORE),
    194: EventType("ev_PICRQ", "Picture requested from expander", EventCategory.INFO),
    195: EventType("ev_PICTKN", "Picture taken and stored on expander", EventCategory.PICTURE),
    196: EventType("ev_PICSNT", "Pic sent OH", EventCategory.INFO),
    197: EventType("ev_OHKM", "Encryption key mismatch between ATS Panel and OH receiver", EventCategory.TROUBLE),
    198: EventType("ev_PICGPRSLIM", "Picture reports over GPRS limit reached", EventCategory.PICTURE),
    199: EventType("ev_PICETHLIM", "Picture reports over ETH limit reached", EventCategory.PICTURE),
    200: EventType("ev_PICLIM", "Picture limit exceeded", EventCategory.PICTURE),
    201: EventType("ev_PEBMEMFULL", "ATS1238 picture memory is full", EventCategory.PICTURE),
    202: EventType("ev_PEBMEMWRC90P", "ATS1238 flash memory reached 90% of write cycles", EventCategory.TROUBLE),
    203: EventType("ev_GETIMGFAIL", "Failed to get picture from the ATS1238", EventCategory.PICTURE),
    204: EventType("ev_PICDEL", "Pictures deleted from ATS1238 and cameras", EventCategory.INFO),
    205: EventType("ev_CAMMODEFAIL", "Setting of camera mode failed", EventCategory.TROUBLE),
    206: EventType("ev_TS", "Test Start", EventCategory.INFO),
    207: EventType("ev_TE", "Test End", EventCategory.INFO),
    208: EventType("ev_LU", "Local programming fail", EventCategory.TROUBLE),
    209: EventType("ev_BRAM", "Detector masked restore", EventCategory.RESTORE),
    210: EventType("ev_BTAM", "Detector masked when disarmed", EventCategory.TROUBLE),
    211: EventType("ev_BRFT", "Detector fault restore", EventCategory.RESTORE),
    212: EventType("ev_BTFT", "Detector fault when disarmed", EventCategory.TROUBLE),
    213: EventType("ev_PICMMSLIM", "MMS reports limit reached", EventCategory.TROUBLE),
    214: EventType("ev_TSDGP", "Test Start", EventCategory.INFO),
    215: EventType("ev_TEDGP", "Test End", EventCategory.INFO),
    216: EventType("ev_TSSYS", "Test Start", EventCategory.INFO),
    217: EventType("ev_TESYS", "Test End", EventCategory.INFO),
    218: EventType("ev_YPDGP", "Power supply trouble", EventCategory.TROUBLE),
    219: EventType("ev_YQDGP", "Power supply restored", EventCategory.RESTORE),
    220: EventType("ev_XHDL", "RF jamming restore (dialler)", EventCategory.RESTORE),
    221: EventType("ev_XQDL", "RF jamming (dialler)", EventCategory.TROUBLE),
    222: EventType("ev_XRFOB", "Fob low battery restore", EventCategory.RESTORE),
    223: EventType("ev_XTFOB", "Fob low battery", EventCategory.TROUBLE),
    224: EventType("ev_TAAM", "Detector masked when unset", EventCategory.ALARM),
    225: EventType("ev_TRAM", "Detector masked restore", EventCategory.ALARM),
    226: EventType("ev_TAFT", "Detector fault when unset", EventCategory.ALARM),
    227: EventType("ev_TRFT", "Detector fault restore", EventCategory.ALARM),
    228: EventType("ev_BVDGP", "Alarm confirm (Exp)", EventCategory.ALARM),
    229: EventType("ev_BVDGPS", "Alarm confirm (DGP siren)", EventCategory.ALARM),
    230: EventType("ev_BVRAS", "Alarm confirm (Rkp)", EventCategory.ALARM),
    231: EventType("ev_BWDGP", "Restore confirmed alarm (Exp)", EventCategory.RESTORE),
    232: EventType("ev_BWDGPS", "Restore confirmed alarm (DGP siren)", EventCategory.RESTORE),
    233: EventType("ev_BWRAS", "Restore confirmed alarm (Rkp)", EventCategory.RESTORE),
    234: EventType("ev_HAZN", "Duress (Zone)", EventCategory.ALARM),
    235: EventType("ev_HRZN", "Duress restore (Zone)", EventCategory.RESTORE),
    236: EventType("ev_BVRASC", "Alarm Confirm from Keypad Communication Fail", EventCategory.ALARM),
    237: EventType("ev_BVDGPC", "Alarm Confirm from Expander Communication Fail", EventCategory.ALARM),
    238: EventType("ev_BWRASC", "Restore Confirmed Alarm from Keypad Communication Fail", EventCategory.ALARM),
    239: EventType("ev_BWDGPC", "Restore Confirmed Alarm from Expander Communication Fail", EventCategory.ALARM),
    240: EventType("ev_YTZN", "Aux batt fault", EventCategory.TROUBLE),
    241: EventType("ev_YRZN", "Aux batt rest.", EventCategory.RESTORE),
    242: EventType("ev_YPOVDGP", "Power supply overvoltage trouble (Exp)", EventCategory.TROUBLE),
    243: EventType("ev_YTDGP", "Battery test on DGP failed", EventCategory.TROUBLE),
    244: EventType("ev_YRDGP", "Battery test on DGP passed", EventCategory.INFO),
    245: EventType("ev_REP_SUCCESS", "Report OK", EventCategory.INFO),
    246: EventType("ev_REP_FAIL", "Report Fail", EventCategory.TROUBLE),
    247: EventType("ev_REP_CONNFAIL", "Connect Fail", EventCategory.TROUBLE),
    248: EventType("ev_YRDL", "Dlr Batt.Rest", EventCategory.RESTORE),
    249: EventType("ev_YTDL", "Dlr Batt.Fail", EventCategory.TROUBLE),
    250: EventType("ev_YCMIDL", "Communications device fault", EventCategory.TROUBLE),
    251: EventType("ev_YKMIDL", "Communications device restore", EventCategory.RESTORE),
    252: EventType("ev_YCMOD", "Module reset", EventCategory.INFO),
    253: EventType("ev_YKMOD", "Module ready", EventCategory.INFO),
    254: EventType("ev_ALTCBACKPC", "Alternate PC connection established", EventCategory.INFO),
    255: EventType("ev_INHLIM", "Inhibit limit", EventCategory.TROUBLE),
    256: EventType("ev_ISOLLIM", "Isolate limit", EventCategory.TROUBLE),
    257: EventType("ev_SHULIM", "Shunt limit", EventCategory.TROUBLE),
    258: EventType("ev_INHLIMR", "Inhibit limit restore", EventCategory.RESTORE),
    259: EventType("ev_ISOLLIMR", "Isolate limit restore", EventCategory.RESTORE),
    260: EventType("ev_SHULIMR", "Shunt limit restore", EventCategory.RESTORE),
    261: EventType("ev_ISOLLIMF", "Isolate limit fault", EventCategory.RESTORE),
    262: EventType("ev_ISOLLIMFR", "Isolate limit fault restore", EventCategory.RESTORE),
    263: EventType("ev_ATMEXTTIME", "Extended Unset time", EventCategory.INFO),
    264: EventType("ev_ATMFAILCLOSE", "Failed Auto Set (ATM)", EventCategory.TROUBLE),
    265: EventType("ev_DETTESTOK", "Det. Test OK", EventCategory.INFO),
    266: EventType("ev_DETTESTFAIL", "Det.Test Fail", EventCategory.INFO),
    267: EventType("ev_DETTSTZNOK", "Det. Tested", EventCategory.INFO),
    268: EventType("ev_DETTSTZNFAIL", "Det.Test Fail", EventCategory.INFO),
    269: EventType("ev_AEXITSTOP", "Area Exit Time Stoppped", EventCategory.INFO),
    270: EventType("ev_BATTREP", "Battery replacement", EventCategory.INFO),
    271: EventType("ev_BATTRES", "Battery resistance", EventCategory.INFO),
    272: EventType("ev_SHUNTMSTRON", "Shunt Master ON", EventCategory.INFO),
    273: EventType("ev_SHUNTMSTROFF", "Shunt Master OFF", EventCategory.INFO),
    274: EventType("ev_ZNSHUNTON", "Shunt ON", EventCategory.INFO),
    275: EventType("ev_ZNSHUNTOFF", "Shunt Off", EventCategory.INFO),
    276: EventType("ev_ZNSHUNTFLT", "Shunt Fault", EventCategory.TROUBLE),
    277: EventType("ev_DUR", "Dual Unset request", EventCategory.UNSET),
    278: EventType("ev_RRREPFAIL", "Power up reporting fail", EventCategory.TROUBLE),
    279: EventType("ev_RRREPFAILR", "Power up reporting restore", EventCategory.RESTORE),
    280: EventType("ev_DD", "Access denied, unknown code", EventCategory.ACCESS),
    281: EventType("ev_IUM_NCARD", "Access denied - IUM card not found", EventCategory.IGNORED),
    282: EventType("ev_CODE_ENTER", "PIN entered by user", EventCategory.IGNORED),
    283: EventType("ev_USRG_FLOOR", "Access granted: Floor", EventCategory.IGNORED),
    284: EventType("ev_DOOR_AUNLOCK", "Door unlocked - auto unlock", EventCategory.IGNORED),
    285: EventType("ev_DOOR_ALOCK", "Door locked - auto lock", EventCategory.IGNORED),
    286: EventType("ev_DOOR_EGRESS", "Request to exit granted at door", EventCategory.IGNORED),
    287: EventType("ev_DOOR_DISABLE", "Door disabled", EventCategory.IGNORED),
    288: EventType("ev_DOOR_ENABLE", "Door enabled", EventCategory.IGNORED),
    289: EventType("ev_DOOR_UNSECURE", "Door unlocked", EventCategory.IGNORED),
    290: EventType("ev_DOOR_SECURE", "Door closed and locked", EventCategory.IGNORED),
    291: EventType("ev_DOOR_FORCED", "Door forced", EventCategory.IGNORED),
    292: EventType("ev_DOOR_FORCED_R", "Door forced restored", EventCategory.IGNORED),
    293: EventType("ev_DOOR_OPEN_TOL", "Door open too long", EventCategory.IGNORED),
    294: EventType("ev_DOOR_OPEN_TOL_R", "Door open too long restored", EventCategory.IGNORED),
    295: EventType("ev_DOOR_OPEN", "Door open", EventCategory.IGNORED),
    296: EventType("ev_DOOR_OPEN_R", "Door open restored", EventCategory.IGNORED),
    297: EventType("ev_HSU_TO_LESS", "Too less HSU behind door.", EventCategory.IGNORED),
    298: EventType("ev_HSU_TOO_LESS_R", "Too few HSU behind door restored", EventCategory.IGNORED),
    299: EventType("ev_HSU_ALARM", "Too few HSU behind door - warning activated", EventCategory.IGNORED),
    300: EventType("ev_HSU_ALARM_R", "Too few HSU behind door - warning stopped", EventCategory.IGNORED),
    301: EventType("ev_USR_ULOCK_DOOR", "Door unlocked by user", EventCategory.IGNORED),
    302: EventType("ev_USR_LOCK_DOOR", "Door locked by user", EventCategory.IGNORED),
    303: EventType("ev_USRG_SPASS", "Access granted: soft passback", EventCategory.IGNORED),
    304: EventType("ev_USRG_REGION", "Access granted: region", EventCategory.IGNORED),
    305: EventType("ev_USRG_TIM_IN", "Access granted: time in", EventCategory.IGNORED),
    306: EventType("ev_USRG_TIM_OUT", "Access granted: time out", EventCategory.IGNORED),
    307: EventType("ev_USRD_SYSCODE", "Access denied: invalid site code", EventCategory.IGNORED),
    308: EventType("ev_USRD_CODE", "Access denied: invalid code", EventCategory.IGNORED),
    309: EventType("ev_USRD_DOOR", "Access denied: invalid door", EventCategory.IGNORED),
    310: EventType("ev_USRD_TIMZN", "Access denied: invalid timezone", EventCategory.IGNORED),
    311: EventType("ev_USRD_AARM", "Access denied: area not disarmed", EventCategory.IGNORED),
    312: EventType("ev_USRD_HPASS", "Access denied: hard passback", EventCategory.IGNORED),
    313: EventType("ev_USRD_PIN", "Access denied: invalid PIN", EventCategory.IGNORED),
    314: EventType("ev_USRD_TWOCARDS", "Access denied: two card violation", EventCategory.IGNORED),
    315: EventType("ev_USRD_TIM_IN", "Access denied: time in", EventCategory.IGNORED),
    316: EventType("ev_USRD_TIM_OUT", "Access denied: time out", EventCategory.IGNORED),
    317: EventType("ev_USRD_HSR", "Access denied: to few HSU users", EventCategory.IGNORED),
    318: EventType("ev_TRACE_USR", "User trace", EventCategory.IGNORED),
    319: EventType("ev_TRACE_DOOR", "Door trace", EventCategory.IGNORED),
    320: EventType("ev_USRD_DCTRL", "User access denied", EventCategory.IGNORED),
    321: EventType("ev_USRG_DCTRL", "User access granted", EventCategory.IGNORED),
    322: EventType("ev_HA_DCTRL", "Duress", EventCategory.ALARM),
    323: EventType("ev_HR_DCTRL", "Duress restore", EventCategory.RESTORE),
    324: EventType("ev_RFUSTART", "Remote firmware upgrade started", EventCategory.INFO),
    325: EventType("ev_RFUFAIL", "Remote firmware upgrade failed", EventCategory.INFO),
    326: EventType("ev_RFUCANCEL", "Remote firmware upgrade canceled", EventCategory.INFO),
    327: EventType("ev_RFUOK", "Remote firmware upgrade finished", EventCategory.INFO),
    328: EventType("ev_TARDR", "Reader tamper", EventCategory.ALARM),
    329: EventType("ev_TRRDR", "Reader tamper restore", EventCategory.RESTORE),
    330: EventType("ev_ETRDRC", "Reader communication fail", EventCategory.TROUBLE),
    331: EventType("ev_ERRDRC", "Reader communication fail restore", EventCategory.RESTORE),
    332: EventType("ev_ERVOC", "Audio device trouble restore", EventCategory.RESTORE),
    333: EventType("ev_ERVOCC", "Audio device communication restore", EventCategory.RESTORE),
    334: EventType("ev_ETVOC", "Audio trouble", EventCategory.TROUBLE),
    335: EventType("ev_ETVOCC", "Audio device communication fail", EventCategory.TROUBLE),
    336: EventType("ev_RRVOC", "Power up Audio device", EventCategory.INFO),
    337: EventType("ev_TAVOC", "Tamper Audio device", EventCategory.ALARM),
    338: EventType("ev_TRVOC", "Tamper Audio device restore", EventCategory.RESTORE),
    339: EventType("ev_UBVOC", "Audio device bypass", EventCategory.INFO),
    340: EventType("ev_UUVOC", "Audio device unbypass", EventCategory.INFO),
    341: EventType("ev_BVVOC", "Alarm confirm", EventCategory.ALARM),
    342: EventType("ev_BWVOC", "Restore confirmed alarm", EventCategory.RESTORE),
    343: EventType("ev_BVVOCC", "Alarm confirm", EventCategory.ALARM),
    344: EventType("ev_BWVOCC", "Restore confirmed alarm", EventCategory.RESTORE),
    345: EventType("ev_HVRDR", "Confirmed panic alarm", EventCategory.ALARM),
    346: EventType("ev_HWRDR", "Restore confirmed panic alarm", EventCategory.RESTORE),
    347: EventType("ev_HVRAS", "Confirmed panic alarm", EventCategory.ALARM),
    348: EventType("ev_HWRAS", "Restore confirmed panic alarm", EventCategory.RESTORE),
    349: EventType("ev_HVDGP", "Confirmed panic alarm", EventCategory.ALARM),
    350: EventType("ev_HWDGP", "Restore confirmed panic alarm", EventCategory.RESTORE),
    351: EventType("ev_HVDGPS", "Confirmed panic alarm", EventCategory.ALARM),
    352: EventType("ev_HWDGPS", "Restore confirmed panic alarm", EventCategory.RESTORE),
    353: EventType("ev_BVDL", "Alarm confirm", EventCategory.ALARM),
    354: EventType("ev_BWDL", "Restore confirmed alarm", EventCategory.RESTORE),
    355: EventType("ev_HVDL", "Confirmed panic alarm", EventCategory.ALARM),
    356: EventType("ev_HWDL", "Restore confirmed panic alarm", EventCategory.RESTORE),
}


# Class ID to readable string mapping
CLASS_ID_STRINGS: dict[int, str] = {
    0: "Zone",
    1: "Area",
    2: "User Group",
    3: "DGP",
    5: "DGP0",
    6: "User",
    7: "Output",
    8: "Panel",
    9: "RAS",
    10: "Central Station",
    11: "PC Connection",
    14: "Output",
    15: "CEV Filter",
    16: "User",
    17: "System",
    19: "Trigger",
    20: "Calendar",
    25: "FOB",
    26: "Camera",
    32: "Area Group",
    35: "Region",
    36: "Door",
    37: "Door Group",
    39: "Special Day",
    41: "Reader",
    42: "Audio Device",
    43: "Notification",
}


def get_event_type(event_id: int) -> EventType:
    """Get event type by ID, returning unknown type if not found."""
    return EVENT_TYPES.get(
        event_id,
        EventType(
            f"UNKNOWN_0x{event_id:04x}",
            "Unknown event type",
            EventCategory.UNKNOWN,
        ),
    )


def get_class_name(class_id: int) -> str:
    """Get class name by ID, returning 'Unknown' if not found."""
    return CLASS_ID_STRINGS.get(class_id, f"Unknown ({class_id})")
